version: '3.7'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.example.com' 
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com' # Change this to match the hostname above
        # Add any other GitLab configuration here
    ports:
      - '0.0.0.0:8081:80'    
      - '443:443'  
      - '22:22'   
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'


  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - '0.0.0.0:5050:8080'  
      - '0.0.0.0:50000:50000' 
    volumes:
      - 'jenkins-data:/var/jenkins_home'

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  jenkins-data:
